# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moccafe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  use_frameworks!

  # Pods for moccafe

  target 'moccafeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moccafeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
